[package]
name = "ieee754-interpreter"
version = "0.1.0"
authors = ["FliegendeWurst <2012gdwu@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
